name: AGM-Local
values:
  - key: base_url_auth
    value: 'http://localhost:8002'
    enabled: true
    type: default
  - key: base_url_asistencias
    value: 'http://localhost:8005'
    enabled: true
    type: default
  - key: base_url_reportes
    value: 'http://localhost:8007'
    enabled: true
    type: default
  - key: materia_id
    value: mat-001
    enabled: true
    type: default
  - key: docente_id
    value: doc-001
    enabled: true
    type: default
  - key: alumno_id
    value: alu-001
    enabled: true
    type: default
  - key: token_qr
    value: token-example-123
    enabled: true
    type: default
  - key: base_url_docentes
    value: 'http://localhost:8003'
    enabled: true
    type: default
  - key: base_url_periodos
    value: 'http://localhost:8001'
    enabled: true
    type: default
  - key: base_url_notificaciones_grpc
    value: 'localhost:50056'
    enabled: true
    type: default
  - key: base_url_docentes_grpc
    value: 'localhost:50053'
    enabled: true
    type: default
  - key: base_url_periodos_grpc
    value: 'localhost:50052'
    enabled: true
    type: default
  - key: base_url_asistencias_grpc
    value: 'localhost:50055'
    enabled: true
    type: default
  - key: base_url_reportes_grpc
    value: 'localhost:50057'
    enabled: true
    type: default
