name: AGM-Local
values:
  - key: base_url_auth
    value: 'http://localhost/api/auth'
    enabled: true
    type: default
  - key: base_url_asistencias
    value: 'http://localhost/api/asistencias'
    enabled: true
    type: default
  - key: base_url_reportes
    value: 'http://localhost/api/reportes'
    enabled: true
    type: default
  - key: materia_id
    value: '25303'
    enabled: true
    type: default
  - key: docente_id
    value: '1'
    enabled: true
    type: default
  - key: alumno_id
    value: '1'
    enabled: true
    type: default
  - key: auth_token
    value: ''
    enabled: true
    type: default
  - key: docente_email
    value: docente@buap.mx
    enabled: true
    type: default
  - key: alumno_email
    value: alumno@buap.mx
    enabled: true
    type: default
  - key: password
    value: password123
    enabled: true
    type: default
  - key: base_url_docentes
    value: 'http://localhost/api/docentes'
    enabled: true
    type: default
  - key: base_url_periodos
    value: 'http://localhost/api/periodos'
    enabled: true
    type: default
  - key: base_url_calificaciones
    value: 'http://localhost/api/calificaciones'
    enabled: true
    type: default
  - key: base_url_notificaciones_grpc
    value: 'localhost:50056'
    enabled: true
    type: default
  - key: base_url_docentes_grpc
    value: 'localhost:50053'
    enabled: true
    type: default
  - key: base_url_periodos_grpc
    value: 'localhost:50052'
    enabled: true
    type: default
  - key: base_url_asistencias_grpc
    value: 'localhost:50055'
    enabled: true
    type: default
  - key: base_url_reportes_grpc
    value: 'localhost:50057'
    enabled: true
    type: default
