name: agm_system
services:
  # Motor de Postgres para todos los microservicios
  postgres-db:
    image: postgres:15-alpine
    container_name: agm_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - agm_db_data:/var/lib/postgresql/data
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql

  # SMTP para captura de correos en local
  smtp4dev:
    image: rnwood/smtp4dev
    container_name: agm_smtp
    ports:
      - "5001:80"
      - "25:25"

  # Caché para sesiones temporales de códigos QR
  redis-db:
    image: redis:7-alpine
    container_name: agm_redis_db
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: agm_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # MS-1 Autenticación y Autorización
  ms-auth:
    build:
      context: ./microservices/ms-auth
      dockerfile: Dockerfile
    container_name: agm_ms_auth
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=clave_super_secreta_desarrollo_agm
      - DATABASE_URL=postgresql://postgres:root@postgres-db:5432/agm_auth_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RESET_PASSWORD_TOKEN_EXPIRE_MINUTES=30
      - RESET_PASSWORD_EXPOSE_TOKEN=true
    depends_on:
      - postgres-db
      - rabbitmq

  # MS-5 Asistencias QR
  ms-asistencias:
    build:
      context: ./microservices/ms-asistencias
      dockerfile: Dockerfile
    container_name: agm_ms_asistencias
    restart: always
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres-db:5432/attendance_db
      - REDIS_URL=redis://redis-db:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres-db
      - redis-db
      - rabbitmq
    
  ms-notificaciones:
      build: 
        context: ./microservices/ms-notificaciones
        dockerfile: Dockerfile
      container_name: agm_ms_notificaciones
      restart: always
      environment:
        - DATABASE_URL=postgresql://postgres:root@postgres-db:5432/agm_notificaciones_db
        - SMTP_HOST=smtp4dev
        - SMTP_PORT=25
        - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
        - MAIL_FROM=Sistema AGM <noreply@agm.local>
        - FRONTEND_URL=http://localhost:4200
      depends_on:
        - postgres-db
        - smtp4dev
        - rabbitmq

  # MS-3 Docentes & Alumnos
  ms-docentes:
    build:
      context: ./microservices/ms-docentes
      dockerfile: Dockerfile
    container_name: agm_ms_docentes
    restart: always
    ports:
      - "8003:8003"
    environment:
      - DB_URL=postgresql://postgres:root@postgres-db:5432/agm_docentes_db
      - REST_PORT=8003
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - NOTIFY_DOCENTE_WHITELIST=
      - NOTIFY_ALUMNO_WHITELIST=
    depends_on:
      - postgres-db
      - rabbitmq

  # MS-4 Calificaciones
  ms-calificaciones:
    build:
      context: ./microservices/ms-calificaciones
      dockerfile: Dockerfile
    container_name: agm_ms_calificaciones
    restart: always
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres-db:5432/agm_calificaciones_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres-db
      - rabbitmq

  ms-periodos-materias:
    build:
      context: ./microservices/ms-periodos-materias
      dockerfile: Dockerfile
    container_name: agm_ms_periodos_materias
    restart: always
    environment:
      - SECRET_KEY=clave_super_secreta_desarrollo_agm
      - ALLOWED_HOSTS=localhost,127.0.0.1,ms-periodos-materias
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=agm_periodos_materias_db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "8001:8000"
    depends_on:
      - postgres-db
      - rabbitmq

  # MS-7 Reportes
  ms-reportes:
    build:
      context: ./microservices/ms-reportes
      dockerfile: Dockerfile
    container_name: agm_ms_reportes
    restart: always
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres-db:5432/reports_db
      - JWT_SECRET=clave_super_secreta_desarrollo_agm
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres-db
      - ms-periodos-materias
      - ms-docentes
      - ms-asistencias
      - rabbitmq

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: agm_api_gateway
    restart: always
    ports:
      - "9000:9000"
    environment:
      - MS_AUTH_HOST=ms-auth
      - MS_PERIODOS_HOST=ms-periodos-materias
      - MS_DOCENTES_HOST=ms-docentes
      - MS_CALIFICACIONES_HOST=ms-calificaciones
      - MS_ASISTENCIAS_HOST=ms-asistencias
      - MS_REPORTES_HOST=ms-reportes
      - PORT=9000
    depends_on:
      - ms-auth
      - ms-periodos-materias
      - ms-docentes
      - ms-asistencias

volumes:
  agm_db_data:
