version: '3.8'

services:
  # Se configura un solo motor de Postgres para todos los microservicios
  postgres-db:
    image: postgres:15-alpine
    container_name: agm_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - agm_db_data:/var/lib/postgresql/data
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
  smtp4dev:
    image: rnwood/smtp4dev
    container_name: agm_smtp
    ports:
      - "5000:80"
      - "25:25"
volumes:
  agm_db_data: