events {
    worker_connections 1024;
}

http {
    server {
        # puerto 80
        listen 80;

        # ms-1 auth    
        location /api/auth/ {
            proxy_pass http://ms-auth:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ms-2 periodos materias
        location /api/periodos/ {
            proxy_pass http://ms-periodos-materias:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ms-3 docentes alumnos
        location /api/docentes/ {
            proxy_pass http://ms-docentes:8003/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 5. ms-4 calificaciones
        location /api/calificaciones/ {
            proxy_pass http://ms-calificaciones:8004/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ms-5 asistencias
        location /api/asistencias/ {
            proxy_pass http://ms-asistencias:8005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ms-6 notificaciones no está proque es interno (full grpc)

        # ms-7 reportes
        location /api/reportes/ {
            proxy_pass http://ms-reportes:8007/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}