services:
  ms-periodos:
    build: .
    container_name: ms-periodos
    ports:
      - "8000:8000"
      - "50051:50051"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: agm_periodos_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      GRPC_PORT: 50051
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-periodos
    environment:
      POSTGRES_DB: agm_periodos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
