# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notificaciones.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notificaciones.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14notificaciones.proto\x12\x0enotificaciones\"L\n\x11\x42ienvenidaRequest\x12\x10\n\x08\x61lumnoId\x18\x01 \x01(\t\x12\x11\n\tmateriaId\x18\x02 \x01(\t\x12\x12\n\nclaveUnica\x18\x03 \x01(\t\"2\n\x0b\x42\x61jaRequest\x12\x10\n\x08\x61lumnoId\x18\x01 \x01(\t\x12\x11\n\tdocenteId\x18\x02 \x01(\t\")\n\x14\x43ierreMateriaRequest\x12\x11\n\tmateriaId\x18\x01 \x01(\t\"4\n\x14ResetPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\">\n\x14NotificacionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x88\x03\n\x15NotificacionesService\x12Y\n\x0eSendBienvenida\x12!.notificaciones.BienvenidaRequest\x1a$.notificaciones.NotificacionResponse\x12R\n\rSendBajaNotif\x12\x1b.notificaciones.BajaRequest\x1a$.notificaciones.NotificacionResponse\x12_\n\x11SendCierreMateria\x12$.notificaciones.CierreMateriaRequest\x1a$.notificaciones.NotificacionResponse\x12_\n\x11SendResetPassword\x12$.notificaciones.ResetPasswordRequest\x1a$.notificaciones.NotificacionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notificaciones_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIENVENIDAREQUEST']._serialized_start=40
  _globals['_BIENVENIDAREQUEST']._serialized_end=116
  _globals['_BAJAREQUEST']._serialized_start=118
  _globals['_BAJAREQUEST']._serialized_end=168
  _globals['_CIERREMATERIAREQUEST']._serialized_start=170
  _globals['_CIERREMATERIAREQUEST']._serialized_end=211
  _globals['_RESETPASSWORDREQUEST']._serialized_start=213
  _globals['_RESETPASSWORDREQUEST']._serialized_end=265
  _globals['_NOTIFICACIONRESPONSE']._serialized_start=267
  _globals['_NOTIFICACIONRESPONSE']._serialized_end=329
  _globals['_NOTIFICACIONESSERVICE']._serialized_start=332
  _globals['_NOTIFICACIONESSERVICE']._serialized_end=724
# @@protoc_insertion_point(module_scope)
