# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import periodosmaterias_pb2 as periodosmaterias__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in periodosmaterias_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeriodosMateriasServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPeriodoById = channel.unary_unary(
                '/agm.periodosmaterias.v1.PeriodosMateriasService/GetPeriodoById',
                request_serializer=periodosmaterias__pb2.PeriodoIdRequest.SerializeToString,
                response_deserializer=periodosmaterias__pb2.PeriodoResponse.FromString,
                _registered_method=True)
        self.GetPeriodoActivo = channel.unary_unary(
                '/agm.periodosmaterias.v1.PeriodosMateriasService/GetPeriodoActivo',
                request_serializer=periodosmaterias__pb2.Empty.SerializeToString,
                response_deserializer=periodosmaterias__pb2.PeriodoResponse.FromString,
                _registered_method=True)
        self.ListPeriodos = channel.unary_unary(
                '/agm.periodosmaterias.v1.PeriodosMateriasService/ListPeriodos',
                request_serializer=periodosmaterias__pb2.Empty.SerializeToString,
                response_deserializer=periodosmaterias__pb2.PeriodosResponse.FromString,
                _registered_method=True)
        self.GetMateriaById = channel.unary_unary(
                '/agm.periodosmaterias.v1.PeriodosMateriasService/GetMateriaById',
                request_serializer=periodosmaterias__pb2.MateriaIdRequest.SerializeToString,
                response_deserializer=periodosmaterias__pb2.MateriaResponse.FromString,
                _registered_method=True)
        self.GetMateriaByNrc = channel.unary_unary(
                '/agm.periodosmaterias.v1.PeriodosMateriasService/GetMateriaByNrc',
                request_serializer=periodosmaterias__pb2.MateriaByNrcRequest.SerializeToString,
                response_deserializer=periodosmaterias__pb2.MateriaResponse.FromString,
                _registered_method=True)
        self.ListMaterias = channel.unary_unary(
                '/agm.periodosmaterias.v1.PeriodosMateriasService/ListMaterias',
                request_serializer=periodosmaterias__pb2.Empty.SerializeToString,
                response_deserializer=periodosmaterias__pb2.MateriasResponse.FromString,
                _registered_method=True)
        self.ListMateriasByPeriodo = channel.unary_unary(
                '/agm.periodosmaterias.v1.PeriodosMateriasService/ListMateriasByPeriodo',
                request_serializer=periodosmaterias__pb2.MateriaByPeriodoRequest.SerializeToString,
                response_deserializer=periodosmaterias__pb2.MateriasResponse.FromString,
                _registered_method=True)
        self.ListMateriasByDocente = channel.unary_unary(
                '/agm.periodosmaterias.v1.PeriodosMateriasService/ListMateriasByDocente',
                request_serializer=periodosmaterias__pb2.MateriaByDocenteRequest.SerializeToString,
                response_deserializer=periodosmaterias__pb2.MateriasResponse.FromString,
                _registered_method=True)


class PeriodosMateriasServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPeriodoById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeriodoActivo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeriodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMateriaById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMateriaByNrc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMaterias(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMateriasByPeriodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMateriasByDocente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeriodosMateriasServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPeriodoById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeriodoById,
                    request_deserializer=periodosmaterias__pb2.PeriodoIdRequest.FromString,
                    response_serializer=periodosmaterias__pb2.PeriodoResponse.SerializeToString,
            ),
            'GetPeriodoActivo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeriodoActivo,
                    request_deserializer=periodosmaterias__pb2.Empty.FromString,
                    response_serializer=periodosmaterias__pb2.PeriodoResponse.SerializeToString,
            ),
            'ListPeriodos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeriodos,
                    request_deserializer=periodosmaterias__pb2.Empty.FromString,
                    response_serializer=periodosmaterias__pb2.PeriodosResponse.SerializeToString,
            ),
            'GetMateriaById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateriaById,
                    request_deserializer=periodosmaterias__pb2.MateriaIdRequest.FromString,
                    response_serializer=periodosmaterias__pb2.MateriaResponse.SerializeToString,
            ),
            'GetMateriaByNrc': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateriaByNrc,
                    request_deserializer=periodosmaterias__pb2.MateriaByNrcRequest.FromString,
                    response_serializer=periodosmaterias__pb2.MateriaResponse.SerializeToString,
            ),
            'ListMaterias': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMaterias,
                    request_deserializer=periodosmaterias__pb2.Empty.FromString,
                    response_serializer=periodosmaterias__pb2.MateriasResponse.SerializeToString,
            ),
            'ListMateriasByPeriodo': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMateriasByPeriodo,
                    request_deserializer=periodosmaterias__pb2.MateriaByPeriodoRequest.FromString,
                    response_serializer=periodosmaterias__pb2.MateriasResponse.SerializeToString,
            ),
            'ListMateriasByDocente': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMateriasByDocente,
                    request_deserializer=periodosmaterias__pb2.MateriaByDocenteRequest.FromString,
                    response_serializer=periodosmaterias__pb2.MateriasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agm.periodosmaterias.v1.PeriodosMateriasService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agm.periodosmaterias.v1.PeriodosMateriasService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeriodosMateriasService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPeriodoById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodosmaterias.v1.PeriodosMateriasService/GetPeriodoById',
            periodosmaterias__pb2.PeriodoIdRequest.SerializeToString,
            periodosmaterias__pb2.PeriodoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeriodoActivo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodosmaterias.v1.PeriodosMateriasService/GetPeriodoActivo',
            periodosmaterias__pb2.Empty.SerializeToString,
            periodosmaterias__pb2.PeriodoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPeriodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodosmaterias.v1.PeriodosMateriasService/ListPeriodos',
            periodosmaterias__pb2.Empty.SerializeToString,
            periodosmaterias__pb2.PeriodosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMateriaById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodosmaterias.v1.PeriodosMateriasService/GetMateriaById',
            periodosmaterias__pb2.MateriaIdRequest.SerializeToString,
            periodosmaterias__pb2.MateriaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMateriaByNrc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodosmaterias.v1.PeriodosMateriasService/GetMateriaByNrc',
            periodosmaterias__pb2.MateriaByNrcRequest.SerializeToString,
            periodosmaterias__pb2.MateriaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMaterias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodosmaterias.v1.PeriodosMateriasService/ListMaterias',
            periodosmaterias__pb2.Empty.SerializeToString,
            periodosmaterias__pb2.MateriasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMateriasByPeriodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodosmaterias.v1.PeriodosMateriasService/ListMateriasByPeriodo',
            periodosmaterias__pb2.MateriaByPeriodoRequest.SerializeToString,
            periodosmaterias__pb2.MateriasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMateriasByDocente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodosmaterias.v1.PeriodosMateriasService/ListMateriasByDocente',
            periodosmaterias__pb2.MateriaByDocenteRequest.SerializeToString,
            periodosmaterias__pb2.MateriasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
