# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_generated import alumnosdocentes_pb2 as alumnosdocentes__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in alumnosdocentes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocentesAlumnosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAlumnoById = channel.unary_unary(
                '/alumnos.DocentesAlumnosService/GetAlumnoById',
                request_serializer=alumnosdocentes__pb2.IdRequest.SerializeToString,
                response_deserializer=alumnosdocentes__pb2.AlumnoInfo.FromString,
                _registered_method=True)
        self.GetAlumnosByMateria = channel.unary_unary(
                '/alumnos.DocentesAlumnosService/GetAlumnosByMateria',
                request_serializer=alumnosdocentes__pb2.MateriaIdRequest.SerializeToString,
                response_deserializer=alumnosdocentes__pb2.AlumnosListResponse.FromString,
                _registered_method=True)
        self.IsAlumnoEnMateria = channel.unary_unary(
                '/alumnos.DocentesAlumnosService/IsAlumnoEnMateria',
                request_serializer=alumnosdocentes__pb2.AlumnoMateriaRequest.SerializeToString,
                response_deserializer=alumnosdocentes__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.GetDocenteById = channel.unary_unary(
                '/alumnos.DocentesAlumnosService/GetDocenteById',
                request_serializer=alumnosdocentes__pb2.IdRequest.SerializeToString,
                response_deserializer=alumnosdocentes__pb2.DocenteInfo.FromString,
                _registered_method=True)


class DocentesAlumnosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAlumnoById(self, request, context):
        """pdf
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlumnosByMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAlumnoEnMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocenteById(self, request, context):
        """agregado para notificaciones
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocentesAlumnosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAlumnoById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlumnoById,
                    request_deserializer=alumnosdocentes__pb2.IdRequest.FromString,
                    response_serializer=alumnosdocentes__pb2.AlumnoInfo.SerializeToString,
            ),
            'GetAlumnosByMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlumnosByMateria,
                    request_deserializer=alumnosdocentes__pb2.MateriaIdRequest.FromString,
                    response_serializer=alumnosdocentes__pb2.AlumnosListResponse.SerializeToString,
            ),
            'IsAlumnoEnMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAlumnoEnMateria,
                    request_deserializer=alumnosdocentes__pb2.AlumnoMateriaRequest.FromString,
                    response_serializer=alumnosdocentes__pb2.BoolResponse.SerializeToString,
            ),
            'GetDocenteById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocenteById,
                    request_deserializer=alumnosdocentes__pb2.IdRequest.FromString,
                    response_serializer=alumnosdocentes__pb2.DocenteInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alumnos.DocentesAlumnosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alumnos.DocentesAlumnosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocentesAlumnosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAlumnoById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.DocentesAlumnosService/GetAlumnoById',
            alumnosdocentes__pb2.IdRequest.SerializeToString,
            alumnosdocentes__pb2.AlumnoInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlumnosByMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.DocentesAlumnosService/GetAlumnosByMateria',
            alumnosdocentes__pb2.MateriaIdRequest.SerializeToString,
            alumnosdocentes__pb2.AlumnosListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsAlumnoEnMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.DocentesAlumnosService/IsAlumnoEnMateria',
            alumnosdocentes__pb2.AlumnoMateriaRequest.SerializeToString,
            alumnosdocentes__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocenteById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.DocentesAlumnosService/GetDocenteById',
            alumnosdocentes__pb2.IdRequest.SerializeToString,
            alumnosdocentes__pb2.DocenteInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
