# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alumnosdocentes.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'alumnosdocentes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61lumnosdocentes.proto\x12\x07\x61lumnos\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x10MateriaIdRequest\x12\x11\n\tmateriaId\x18\x01 \x01(\t\";\n\x14\x41lumnoMateriaRequest\x12\x10\n\x08\x61lumnoId\x18\x01 \x01(\t\x12\x11\n\tmateriaId\x18\x02 \x01(\t\"\x1e\n\x0c\x42oolResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"7\n\nAlumnoInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"8\n\x0b\x44ocenteInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\";\n\x13\x41lumnosListResponse\x12$\n\x07\x61lumnos\x18\x01 \x03(\x0b\x32\x13.alumnos.AlumnoInfo2\xa9\x02\n\x16\x44ocentesAlumnosService\x12\x38\n\rGetAlumnoById\x12\x12.alumnos.IdRequest\x1a\x13.alumnos.AlumnoInfo\x12N\n\x13GetAlumnosByMateria\x12\x19.alumnos.MateriaIdRequest\x1a\x1c.alumnos.AlumnosListResponse\x12I\n\x11IsAlumnoEnMateria\x12\x1d.alumnos.AlumnoMateriaRequest\x1a\x15.alumnos.BoolResponse\x12:\n\x0eGetDocenteById\x12\x12.alumnos.IdRequest\x1a\x14.alumnos.DocenteInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alumnosdocentes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDREQUEST']._serialized_start=34
  _globals['_IDREQUEST']._serialized_end=57
  _globals['_MATERIAIDREQUEST']._serialized_start=59
  _globals['_MATERIAIDREQUEST']._serialized_end=96
  _globals['_ALUMNOMATERIAREQUEST']._serialized_start=98
  _globals['_ALUMNOMATERIAREQUEST']._serialized_end=157
  _globals['_BOOLRESPONSE']._serialized_start=159
  _globals['_BOOLRESPONSE']._serialized_end=189
  _globals['_ALUMNOINFO']._serialized_start=191
  _globals['_ALUMNOINFO']._serialized_end=246
  _globals['_DOCENTEINFO']._serialized_start=248
  _globals['_DOCENTEINFO']._serialized_end=304
  _globals['_ALUMNOSLISTRESPONSE']._serialized_start=306
  _globals['_ALUMNOSLISTRESPONSE']._serialized_end=365
  _globals['_DOCENTESALUMNOSSERVICE']._serialized_start=368
  _globals['_DOCENTESALUMNOSSERVICE']._serialized_end=665
# @@protoc_insertion_point(module_scope)
