# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import periodos_pb2 as periodos__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in periodos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeriodosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPeriodoById = channel.unary_unary(
                '/agm.periodos.v1.PeriodosService/GetPeriodoById',
                request_serializer=periodos__pb2.PeriodoIdRequest.SerializeToString,
                response_deserializer=periodos__pb2.PeriodoResponse.FromString,
                _registered_method=True)
        self.GetPeriodoActivo = channel.unary_unary(
                '/agm.periodos.v1.PeriodosService/GetPeriodoActivo',
                request_serializer=periodos__pb2.Empty.SerializeToString,
                response_deserializer=periodos__pb2.PeriodoResponse.FromString,
                _registered_method=True)
        self.ListPeriodos = channel.unary_unary(
                '/agm.periodos.v1.PeriodosService/ListPeriodos',
                request_serializer=periodos__pb2.Empty.SerializeToString,
                response_deserializer=periodos__pb2.PeriodosResponse.FromString,
                _registered_method=True)


class PeriodosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPeriodoById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeriodoActivo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeriodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeriodosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPeriodoById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeriodoById,
                    request_deserializer=periodos__pb2.PeriodoIdRequest.FromString,
                    response_serializer=periodos__pb2.PeriodoResponse.SerializeToString,
            ),
            'GetPeriodoActivo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeriodoActivo,
                    request_deserializer=periodos__pb2.Empty.FromString,
                    response_serializer=periodos__pb2.PeriodoResponse.SerializeToString,
            ),
            'ListPeriodos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeriodos,
                    request_deserializer=periodos__pb2.Empty.FromString,
                    response_serializer=periodos__pb2.PeriodosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agm.periodos.v1.PeriodosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agm.periodos.v1.PeriodosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeriodosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPeriodoById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodos.v1.PeriodosService/GetPeriodoById',
            periodos__pb2.PeriodoIdRequest.SerializeToString,
            periodos__pb2.PeriodoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeriodoActivo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodos.v1.PeriodosService/GetPeriodoActivo',
            periodos__pb2.Empty.SerializeToString,
            periodos__pb2.PeriodoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPeriodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periodos.v1.PeriodosService/ListPeriodos',
            periodos__pb2.Empty.SerializeToString,
            periodos__pb2.PeriodosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
