# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: periodos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'periodos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eperiodos.proto\x12\x0f\x61gm.periodos.v1\"\x07\n\x05\x45mpty\"\x1e\n\x10PeriodoIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"|\n\x0ePeriodoMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x14\n\x0c\x66\x65\x63ha_inicio\x18\x03 \x01(\t\x12\x11\n\tfecha_fin\x18\x04 \x01(\t\x12\x15\n\rplan_estudios\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tivo\x18\x06 \x01(\x08\"b\n\x0fPeriodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12-\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1f.agm.periodos.v1.PeriodoMessage\"c\n\x10PeriodosResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12-\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x1f.agm.periodos.v1.PeriodoMessage2\x81\x02\n\x0fPeriodosService\x12U\n\x0eGetPeriodoById\x12!.agm.periodos.v1.PeriodoIdRequest\x1a .agm.periodos.v1.PeriodoResponse\x12L\n\x10GetPeriodoActivo\x12\x16.agm.periodos.v1.Empty\x1a .agm.periodos.v1.PeriodoResponse\x12I\n\x0cListPeriodos\x12\x16.agm.periodos.v1.Empty\x1a!.agm.periodos.v1.PeriodosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'periodos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_PERIODOIDREQUEST']._serialized_start=44
  _globals['_PERIODOIDREQUEST']._serialized_end=74
  _globals['_PERIODOMESSAGE']._serialized_start=76
  _globals['_PERIODOMESSAGE']._serialized_end=200
  _globals['_PERIODORESPONSE']._serialized_start=202
  _globals['_PERIODORESPONSE']._serialized_end=300
  _globals['_PERIODOSRESPONSE']._serialized_start=302
  _globals['_PERIODOSRESPONSE']._serialized_end=401
  _globals['_PERIODOSSERVICE']._serialized_start=404
  _globals['_PERIODOSSERVICE']._serialized_end=661
# @@protoc_insertion_point(module_scope)
