# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reportes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reportes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ereportes.proto\x12\x08reportes\"G\n\rReportRequest\x12\x11\n\tmateriaId\x18\x01 \x01(\t\x12\x0f\n\x07\x66ormato\x18\x02 \x01(\t\x12\x12\n\ndatos_json\x18\x03 \x01(\t\"%\n\x10\x44ocenteIdRequest\x12\x11\n\tdocenteId\x18\x01 \x01(\t\"t\n\x0eReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nfile_bytes\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\"\xa2\x01\n\x0cStatsPeriodo\x12\x16\n\x0eperiodo_nombre\x18\x01 \x01(\t\x12\x16\n\x0emateria_nombre\x18\x02 \x01(\t\x12\x13\n\x0bmateria_nrc\x18\x03 \x01(\t\x12\x15\n\rtotal_alumnos\x18\x04 \x01(\x05\x12\x18\n\x10promedio_general\x18\x05 \x01(\x02\x12\x1c\n\x14porcentaje_aprobados\x18\x06 \x01(\x02\"l\n\x18HistorialDocenteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12(\n\x08periodos\x18\x02 \x03(\x0b\x32\x16.reportes.StatsPeriodo\x12\x15\n\rerror_message\x18\x03 \x01(\t2\x8b\x02\n\x0fReportesService\x12Q\n\x1cGenerateCalificacionesReport\x12\x17.reportes.ReportRequest\x1a\x18.reportes.ReportResponse\x12N\n\x19GenerateAsistenciasReport\x12\x17.reportes.ReportRequest\x1a\x18.reportes.ReportResponse\x12U\n\x13GetHistorialDocente\x12\x1a.reportes.DocenteIdRequest\x1a\".reportes.HistorialDocenteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reportes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTREQUEST']._serialized_start=28
  _globals['_REPORTREQUEST']._serialized_end=99
  _globals['_DOCENTEIDREQUEST']._serialized_start=101
  _globals['_DOCENTEIDREQUEST']._serialized_end=138
  _globals['_REPORTRESPONSE']._serialized_start=140
  _globals['_REPORTRESPONSE']._serialized_end=256
  _globals['_STATSPERIODO']._serialized_start=259
  _globals['_STATSPERIODO']._serialized_end=421
  _globals['_HISTORIALDOCENTERESPONSE']._serialized_start=423
  _globals['_HISTORIALDOCENTERESPONSE']._serialized_end=531
  _globals['_REPORTESSERVICE']._serialized_start=534
  _globals['_REPORTESSERVICE']._serialized_end=801
# @@protoc_insertion_point(module_scope)
