# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reportes_pb2 as reportes__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reportes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportesServiceStub(object):
    """Servicio gRPC que ms-reportes expone hacia otros microservicios internos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCalificacionesReport = channel.unary_unary(
                '/reportes.ReportesService/GenerateCalificacionesReport',
                request_serializer=reportes__pb2.ReportRequest.SerializeToString,
                response_deserializer=reportes__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.GenerateAsistenciasReport = channel.unary_unary(
                '/reportes.ReportesService/GenerateAsistenciasReport',
                request_serializer=reportes__pb2.ReportRequest.SerializeToString,
                response_deserializer=reportes__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.GetHistorialDocente = channel.unary_unary(
                '/reportes.ReportesService/GetHistorialDocente',
                request_serializer=reportes__pb2.DocenteIdRequest.SerializeToString,
                response_deserializer=reportes__pb2.HistorialDocenteResponse.FromString,
                _registered_method=True)


class ReportesServiceServicer(object):
    """Servicio gRPC que ms-reportes expone hacia otros microservicios internos
    """

    def GenerateCalificacionesReport(self, request, context):
        """Genera un reporte de calificaciones en el formato solicitado (pdf | xls)
        Llamado por: ms-calificaciones o el Gateway cuando necesita el archivo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAsistenciasReport(self, request, context):
        """Genera un reporte de asistencias en el formato solicitado (pdf | xls)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistorialDocente(self, request, context):
        """Devuelve el historial de estadísticas de un docente por periodo
        Llamado por: el Gateway para construir el dashboard del docente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCalificacionesReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCalificacionesReport,
                    request_deserializer=reportes__pb2.ReportRequest.FromString,
                    response_serializer=reportes__pb2.ReportResponse.SerializeToString,
            ),
            'GenerateAsistenciasReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAsistenciasReport,
                    request_deserializer=reportes__pb2.ReportRequest.FromString,
                    response_serializer=reportes__pb2.ReportResponse.SerializeToString,
            ),
            'GetHistorialDocente': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistorialDocente,
                    request_deserializer=reportes__pb2.DocenteIdRequest.FromString,
                    response_serializer=reportes__pb2.HistorialDocenteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reportes.ReportesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reportes.ReportesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportesService(object):
    """Servicio gRPC que ms-reportes expone hacia otros microservicios internos
    """

    @staticmethod
    def GenerateCalificacionesReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reportes.ReportesService/GenerateCalificacionesReport',
            reportes__pb2.ReportRequest.SerializeToString,
            reportes__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAsistenciasReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reportes.ReportesService/GenerateAsistenciasReport',
            reportes__pb2.ReportRequest.SerializeToString,
            reportes__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistorialDocente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reportes.ReportesService/GetHistorialDocente',
            reportes__pb2.DocenteIdRequest.SerializeToString,
            reportes__pb2.HistorialDocenteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
