# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calificaciones.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calificaciones.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61lificaciones.proto\x12\x0e\x63\x61lificaciones\"8\n\x0fPromedioRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\x12\x11\n\talumno_id\x18\x02 \x01(\t\"L\n\x10PromedioResponse\x12\x16\n\x0epromedio_final\x18\x01 \x01(\x02\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"$\n\x0eMateriaRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"O\n\x13\x43oncentradoResponse\x12\x38\n\x0e\x63\x61lificaciones\x18\x01 \x03(\x0b\x32 .calificaciones.CalificacionItem\"M\n\x10\x43\x61lificacionItem\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x0c\n\x04nota\x18\x02 \x01(\x02\x12\x18\n\x10\x61\x63tividad_nombre\x18\x03 \x01(\t\"\x8b\x01\n\x14\x45stadisticasResponse\x12\x18\n\x10promedio_general\x18\x01 \x01(\x02\x12\x1f\n\x17total_alumnos_evaluados\x18\x02 \x01(\x05\x12\x1b\n\x13\x63\x61lificacion_maxima\x18\x03 \x01(\x02\x12\x1b\n\x13\x63\x61lificacion_minima\x18\x04 \x01(\x02\x32\xb3\x02\n\x15\x43\x61lificacionesService\x12X\n\x11GetPromedioAlumno\x12\x1f.calificaciones.PromedioRequest\x1a .calificaciones.PromedioResponse\"\x00\x12^\n\x15GetConcentradoMateria\x12\x1e.calificaciones.MateriaRequest\x1a#.calificaciones.ConcentradoResponse\"\x00\x12`\n\x16GetEstadisticasMateria\x12\x1e.calificaciones.MateriaRequest\x1a$.calificaciones.EstadisticasResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calificaciones_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMEDIOREQUEST']._serialized_start=40
  _globals['_PROMEDIOREQUEST']._serialized_end=96
  _globals['_PROMEDIORESPONSE']._serialized_start=98
  _globals['_PROMEDIORESPONSE']._serialized_end=174
  _globals['_MATERIAREQUEST']._serialized_start=176
  _globals['_MATERIAREQUEST']._serialized_end=212
  _globals['_CONCENTRADORESPONSE']._serialized_start=214
  _globals['_CONCENTRADORESPONSE']._serialized_end=293
  _globals['_CALIFICACIONITEM']._serialized_start=295
  _globals['_CALIFICACIONITEM']._serialized_end=372
  _globals['_ESTADISTICASRESPONSE']._serialized_start=375
  _globals['_ESTADISTICASRESPONSE']._serialized_end=514
  _globals['_CALIFICACIONESSERVICE']._serialized_start=517
  _globals['_CALIFICACIONESSERVICE']._serialized_end=824
# @@protoc_insertion_point(module_scope)
