# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calificaciones_pb2 as calificaciones__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in calificaciones_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalificacionesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPromedioAlumno = channel.unary_unary(
                '/calificaciones.CalificacionesService/GetPromedioAlumno',
                request_serializer=calificaciones__pb2.PromedioRequest.SerializeToString,
                response_deserializer=calificaciones__pb2.PromedioResponse.FromString,
                _registered_method=True)
        self.GetConcentradoMateria = channel.unary_unary(
                '/calificaciones.CalificacionesService/GetConcentradoMateria',
                request_serializer=calificaciones__pb2.MateriaRequest.SerializeToString,
                response_deserializer=calificaciones__pb2.ConcentradoResponse.FromString,
                _registered_method=True)
        self.GetEstadisticasMateria = channel.unary_unary(
                '/calificaciones.CalificacionesService/GetEstadisticasMateria',
                request_serializer=calificaciones__pb2.MateriaRequest.SerializeToString,
                response_deserializer=calificaciones__pb2.EstadisticasResponse.FromString,
                _registered_method=True)


class CalificacionesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPromedioAlumno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConcentradoMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEstadisticasMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalificacionesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPromedioAlumno': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromedioAlumno,
                    request_deserializer=calificaciones__pb2.PromedioRequest.FromString,
                    response_serializer=calificaciones__pb2.PromedioResponse.SerializeToString,
            ),
            'GetConcentradoMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConcentradoMateria,
                    request_deserializer=calificaciones__pb2.MateriaRequest.FromString,
                    response_serializer=calificaciones__pb2.ConcentradoResponse.SerializeToString,
            ),
            'GetEstadisticasMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEstadisticasMateria,
                    request_deserializer=calificaciones__pb2.MateriaRequest.FromString,
                    response_serializer=calificaciones__pb2.EstadisticasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calificaciones.CalificacionesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calificaciones.CalificacionesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalificacionesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPromedioAlumno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calificaciones.CalificacionesService/GetPromedioAlumno',
            calificaciones__pb2.PromedioRequest.SerializeToString,
            calificaciones__pb2.PromedioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConcentradoMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calificaciones.CalificacionesService/GetConcentradoMateria',
            calificaciones__pb2.MateriaRequest.SerializeToString,
            calificaciones__pb2.ConcentradoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEstadisticasMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calificaciones.CalificacionesService/GetEstadisticasMateria',
            calificaciones__pb2.MateriaRequest.SerializeToString,
            calificaciones__pb2.EstadisticasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
