services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: agm_academic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - academic_data:/var/lib/postgresql/data

  ms-periodos-materias:
    build:
      context: ./ms-periodos-materias
    container_name: ms-periodos-materias
    restart: unless-stopped
    env_file:
      - ./ms-periodos-materias/.env
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: agm_academic_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      GRPC_PORT: 50051
    depends_on:
      - db
    ports:
      - "8001:8000"
      - "50051:50051"
    volumes:
      - ./ms-periodos-materias:/app

volumes:
  academic_data:
