services:
  periodos-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: agm_periodos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - periodos_data:/var/lib/postgresql/data

  materias-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: agm_materias_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - materias_data:/var/lib/postgresql/data

  ms-periodos:
    build:
      context: ./ms-periodos
    restart: unless-stopped
    env_file:
      - ./ms-periodos/.env
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: periodos-db
      DB_PORT: 5432
      DB_NAME: agm_periodos_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      GRPC_PORT: 50051
    depends_on:
      - periodos-db
    ports:
      - "8001:8000"
      - "50051:50051"
    volumes:
      - ./ms-periodos:/app

  ms-materias:
    build:
      context: ./ms-materias
    restart: unless-stopped
    env_file:
      - ./ms-materias/.env
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: materias-db
      DB_PORT: 5432
      DB_NAME: agm_materias_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      PERIODOS_GRPC_HOST: ms-periodos
      PERIODOS_GRPC_PORT: 50051
    depends_on:
      - materias-db
      - ms-periodos
    ports:
      - "8002:8000"
    volumes:
      - ./ms-materias:/app

volumes:
  periodos_data:
  materias_data:
